name: Security Scan

on:
  workflow_dispatch:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Node Audit
        run: npm audit --audit-level=moderate

      - name: Build Docker Image
        run: docker build -t smartbuild-app .

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: smartbuild-app
          exit-code: '1'
          severity: 'HIGH,CRITICAL'
